### PR TITLE
Feature/VTEX IO Page Layout

### PR DESCRIPTION
**Pull request by leonardoAnjos16**
#### What is the purpose of this pull request?

To add the correct layout (as per [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=2641%3A149733)) to the VTEX IO page of the Developers Portal.

Documented [here](https://www.notion.so/vtexhandbook/Criar-p-gina-VTEX-IO-com-a-estrutura-do-Figma-339d26aefcea4cd2b880d1cbae1b7f17)

#### What problem is this solving?

Currently, the VTEX IO page of the Developers Portal is empty. It should contain the sidebar and some content next to it. This pull request implements that layout and adds some of the content of the page.

#### How should this be manually tested?

Go to [this page](https://deploy-preview-39--elated-hoover-5c29bf.netlify.app/) and check the layout against [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=2641%3A149733) with different breakpoints, keeping in mind the cards in between the "Welcome" and "Other resources" sections will be implemented in future PRs.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by RobsonOlv — APPROVED** [review]
LGTM :rocket:

**Review by JosueFidelis — APPROVED** [review]
LGTM :top:

**Review by JoaoMontenegr0 — APPROVED** [review]
Ótimo! Apenas o header que não alterou para o header do mobile, mas acredito que isso seja outro PR.

**Review by Meyrillan — APPROVED** [review]
LGTM ✨

**Review by amandascm — APPROVED** [review]
LGTM!!

**Pull request merged**
