### PR TITLE
feat(release-note): create release note page and component

### PR DESCRIPTION
**Pull request by melissafalcao**
#### What is the purpose of this pull request?

[More details ](https://www.notion.so/vtexhandbook/Criar-componente-release-notes-c179f61065b24471b9452284aef79c08)📖 

Create Release Notes page and components.

#### What problem is this solving?

We should have a page that shows recent releases. This page should be in timeline format, showing the latest releases with title, description and date. For this we created two components and the page. Please also follow the [additional documentation](https://www.notion.so/vtexhandbook/Criar-componente-release-notes-c179f61065b24471b9452284aef79c08), which contains some questions about the components of this update.

#### How should this be manually tested?

Please go to [this workspace,](https://deploy-preview-37--elated-hoover-5c29bf.netlify.app/updates/release-notes) and check that everything works correctly. Also compare it with the version in the [figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=129%3A28).
#### Screenshots or example usage
image

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by RobsonOlv — APPROVED** [review]
LGTM :rocket:

**Review by leonardoAnjos16 — CHANGES_REQUESTED** [review]
Very nice!! I just noticed you created a page for the release notes inside the `docs` directory, but there already is a page for it inside the `updates` directory. What do you think about moving the code there?

**Review by JosueFidelis — APPROVED** [review]
LGTM :top:

**Review by JosueFidelis — APPROVED** [review]

**Review by amandascm — APPROVED** [review]
LGTM ✔️ 
(to help others reviewing the PR, update the Release Notes section URL provided in the PR description with [https://deploy-preview-37--elated-hoover-5c29bf.netlify.app/updates/release-notes](https://deploy-preview-37--elated-hoover-5c29bf.netlify.app/updates/release-notes))

**Review by leonardoAnjos16 — APPROVED** [review]
LGTM 💯

**Pull request merged**
