### PR TITLE
Feature/What's Next Cards

### PR DESCRIPTION
**Pull request by leonardoAnjos16**
#### What is the purpose of this pull request?

To add the What's Next Card component and instances of it to the Quick Started (VTEX IO) page of the Developer's Portal.

Documented [here](https://www.notion.so/vtexhandbook/Criar-cards-da-p-gina-de-VTEX-IO-52db0485801a4f06bd0022cd3e2b8c23)

#### What problem is this solving?

The Quick Started (VTEX IO) page of the Developer's Portal should have cards leading to introductory documentation.

#### How should this be manually tested?

Go to [this page](https://deploy-preview-54--elated-hoover-5c29bf.netlify.app/docs/vtex-io) and check the cards against [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=6005%3A471890). Try different breakpoints!

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by amandascm — COMMENTED** [review]
Really nice contribution! ✨ 

A small fix to do: the color of the rigth caret inside the card (screenshot below) should be `#A1A8B3` according to the page design.
image

**Review by amandascm — APPROVED** [review]

**Review by JosueFidelis — APPROVED** [review]
LGTM :top:

**Review by melissafalcao — APPROVED** [review]
LGTM 👍🏻

**Review by amandascm — APPROVED** [review]

**Review by RobsonOlv — APPROVED** [review]
LGTM :rocket:

**Review by melissafalcao — APPROVED** [review]
LGTM 👍🏻

**Review by JoaoMontenegr0 — APPROVED** [review]

**Pull request merged**
