### PR TITLE
Feature/markdown preview

### PR DESCRIPTION
**Pull request by RobsonOlv**
#### What is the purpose of this pull request?

Add the markdown editor to help the Documentation Team preview the rendered page before making changes to the documents repository, preventing errors.

#### How should this be manually tested?

Go to [this page](https://deploy-preview-403--elated-hoover-5c29bf.netlify.app/markdown-preview) and try to edit the markdown template previewing changes on the side. (try to force errors)

#### Screenshots or example usage

https://github.com/vtexdocs/devportal/assets/42784961/38ac753c-daf9-422b-bcb2-adc1eae48128

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by aliceoq — APPROVED** [review]
LGTM :star_struck: 

Pro futuro eu acho que seria interessante ter o número das linhas no editor e também poder ajustar o tamanho, porque pra editar tabelas, por exemplo, seria melhor que fosse mais largo.

**Review by leonardoAnjos16 — APPROVED** [review]
LGTM 💯

**Comment by RobsonOlv** [comment]
> LGTM star_struck
> 
> Pro futuro eu acho que seria interessante ter o número das linhas no editor e também poder ajustar o tamanho, porque pra editar tabelas, por exemplo, seria melhor que fosse mais largo.

Por que não agora? :smile:

**Review by aliceoq — APPROVED** [review]
LGTM

**Review by leonardoAnjos16 — APPROVED** [review]

**Comment by ThayllyR** [comment]
LGTM

**Review by ThayllyR — APPROVED** [review]
LGTM

**Pull request merged**
